os:
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode9.4
rvm:
  - 2.2.4
before_install:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - .travis/update-submodule.sh
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
install:
  - gem install slather
  - wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | sudo apt-key add -
  - echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vapor.list
  - sudo apt-get update
  - sudo apt-get install swift vapor
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - swift build
  - swift test
  - vapor xcode -n
  - slather coverage --cobertura-xml --source-directory ./Sources/ --output-directory ./ --scheme AppTests ./GitignoreIO.xcodeproj
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
    - josephblau@gmail.com
deploy:
  provider: heroku
  strategy: git
  app: gitignoreio-stage-swift
  on: master
  api_key:
    secure: In+pMxDoWCe5h2oCi20pCpLGLdiqvP1SuWqTkFm1G1LPtZ7LIcIbxlCgiWGlWqaPnwC5n0VkpOEkOSnFZz2E7ffKQuzonvEBUPl5EFLzfJxeHUDWaaMGWfadx2kR21cx/wTyEZseSqeBm77wbKJKU7D6RqRbCS+MxaavQhaJnKk=
env:
  global:
    - CC_TEST_REPORTER_ID=6133dfb857104f811740c22973bcb412866eba231509f7f8f60a8ad95005ee2b
    - secure: ZubW/TIAZCjYPJYI1mwUtWhY9iAabIQzyeexKGEbcbUuYhdCzZ2Dj7mIjPyOQ0KPwQm3nwWPRXq8V7YnGJMU3ytofu/PTb0gYDGPguVpLj0k7hN3xlxuODQeP2BtiS4uzuXspMfOb14kEkszFqU0qlF/eKnKBtqvva//Iwi2L3I=
